### ISSUE TITLE
is there a way to npm install private packages under private NPM registry? 

### ISSUE THREAD

**Issue by hrgui** [GoogleCloudPlatform/nodejs-docker#118]
**Env**
App Engine

I have a private package in a private NPM registry, and I was wondering if the docker image have access to the corporate proxies where my private NPM registry is - or is that being run on the cloud? 

I got an error like the following when running gcloud app deploy:
```
gcloud --project my-project beta app deploy

2147 error network getaddrinfo ENOTFOUND my-private-registry.org my-private-registry.org:80
2148 error network This is most likely not a problem with npm itself
2148 error network and is related to network connectivity.
2148 error network In most cases you are behind a proxy or have bad network settings.
```

**Comment by hrgui** [comment]
There is a workaround fortunately for this:

1. `npm pack your_private_package` This will package the private package in the directory currently located in, in `.tgz` format. For this example, it will save it as `your_private_package-1.0.0.tgz`.
2. `npm install --save your_private_package-1.0.0.tgz`

**Comment by DominicKramer** [comment]
Thank you for your feedback.  I'm glad you have found a workaround.  Are you deploying your app to App Engine Flexible using `gcloud [beta] app deploy`?  I will update this thread with any new information about this issue.  Thanks.

**Comment by hrgui** [comment]
@DominicKramer , yes I am using gcloud beta app deploy, the beta version

**Comment by ofrobots** [comment]
Hi @hrgui: The deployment works via building a docker container which then gets deployed to App Engine. The actual docker build happens on the [Container Builder](https://cloud.google.com/container-builder/) service.

If your private packages are on npm, or another registry, reachable on the public internet, we should be able to `npm install` them into the container. If the registry is behind a corporate firewall, the container builder won't be able to fetch those modules automatically, because the Container Builder service won't be able to access that server.

The work-arounds at the moment seem to be:
* Include a tarball of your private module into your source and use a custom Dockerfile (as you have done above).
* Vendor a copy of the source code for your module directly (e.g. using `git submodule` or `git subtree`).
* Use a public registry that offers private packages.

I'll look around for other solutions, but those are the ones I can think of at the moment.

**Comment by hrgui** [comment]
@ofrobots Thanks for the explanation. I was wondering why it deploy had nothing to do with my Docker instance that I have in my Mac. 

Unfortunately, my registry is behind a corporate firewall, which is probably the reason why those modules weren't accessible. I think the workarounds that you have listed should be sufficient for my needs.

**Comment by ofrobots** [comment]
Oh, I learned of another option: build your docker image locally using docker, and then deploy the image to App Engine.

Here's an example:

```sh
docker build -t gcr.io/my-project-name:some-tag .
gcloud docker -- push gcr.io/my-project-name:some-tag
gcloud app deploy --image-url gcr.io/my-project-name:some-tag
```

This way, the build is performed on your machine locally, so it should be able to access any private servers that you can access locally.

Let us know if this helpds.

**Comment by hrgui** [comment]
@ofrobots I think that is the best solution to my question, in which I can now close this issue.

**Comment by z-vr** [comment]
@ofrobots @hrgui when Docker builds locally, it doesn't have the ssh key in the container. This is the correct solution https://vsupalov.com/build-docker-image-clone-private-repo-ssh-key/

**Comment by boredland** [comment]
did anybody find a way to deploy to app engine standard?
