### ISSUE TITLE
Dev dependencies not found after installing

### ISSUE THREAD

**Issue by iddan** [GoogleCloudPlatform/nodejs-docker#155]
Been trying to `FROM` this image and specified `npm install` stage as in the manual but when running npm script: `npm run build` dev dependency (or more) where missing.

Is this the expected behaviour? For me it was kinda odd.

**Comment by DominicKramer** [comment]
The Dockerfile for the `gcr.io/google-appengine/nodejs` image contains the line
```Dockerfile
ENV NODE_ENV production
```
that sets the `NODE_ENV` environment variable to `production`.  That could explain why the `npm install` is not installing dev dependencies.

Try using `NODE_ENV=development npm install` instead of just `npm install` in your Dockerfile.  That should install the dev dependencies.  If you are still having problems, let us know.  Thanks.

**Comment by DominicKramer** [comment]
I'm going to close this issue.  If you are still having problems, please let me know.

**Comment by AkashBabu** [comment]
@DominicKramer Thanks a lot for pointing out that `npm install` would not install devDependencies if NODE_ENV=production
