### ISSUE TITLE
Adding packagaes

### ISSUE THREAD

**Issue by mbrevda** [GoogleCloudPlatform/nodejs-docker#169]
Hi -

I was wondering about the polices for this image regarding adding packages. Specifically, I was wondering if we could get `gcloud` preinstalled? I would also be interested in `poppler-utils` (pfd information and manipulation). Would PR for these be desired?

My use case is having these packages available in GCF.

Thanks!

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  I will talk to the appropriate teams to determine if this is possible.

**Comment by DominicKramer** [comment]
After looking at this more, we would prefer not adding additional packages to the base image unless there is a need by many users for those packages.

This is first because the additional packages will cause the image to become bigger, and we don't want the image to be bigger than it needs to.

Second, if you need, you can create a custom Dockerfile derived from the base image in this repo and add the custom packages that you need.

Based on this, I am going to close this issue at this time, but let me know if you want to discuss this topic more.

**Comment by mbrevda** [comment]
My goal in adding the packages was to make them available in GCF. Is there
another way to do that?
