### ISSUE TITLE
[Discussion] Should we consider using forever/nodemon/pm2 by default?

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/nodejs-docker#45]
This came up in another thread, and I'm looking for opinions :)  Right now we by default just run `npm start` in the generated Dockerfile to bootstrap the node process.   If the process goes down, we have Docker just restart it automatically.  Is there merit to using a process manager as well?

You can `npm install --save-dev forever` and then update your `package.json` to include a specific start command - but should we consider doing something more fancy?  

@dlorenc @raggi @ofrobots @jmdobry @stephenplusplus

**Comment by jmdobry** [comment]
I'm not sure it makes much sense to do anything beyond `npm start`, because the user can put _anything_ there. Like you mentioned, the user might themselves be starting their app with `forever` or `pm2`, or be executing a `.sh` script, or spawning worker processes manually with the `cluster` module, or who knows what.

I think it makes more sense to invest in making the Node.js Trace and Debug modules as nice as possible, with clear links in the console's App Engine dashboard to relevant Trace/Debug/Log views, so whatever processes the user `does` spawn can be easily monitored.

Unless we decide to impose constraints on what processes _can_ be started, then I'm not sure it even makes sense to have Docker try to restart anything. Depending on what the user's `npm start` command does, could Docker make a mess of things by re-running it?

If we want better process management, then I think we need an all-or-nothing approach. Here are the two options I see:

1) `npm start` - User does everything
  - User starts their own process(es), does their own clustering, process monitoring/restarting
  - Has complete control, but has to do all this stuff manually
  - Must install `cloud-nodejs-trace`, `cloud-trace-debug`

2) `"main": "server.js"` - We do everything
  - User specifies the file that starts a web app worker, e.g. file that does `server.listen(...)`
  - Has less control, but doesn't have to worry about this stuff anymore
  - We wrap their `main` file in a process manager (e.g. `pm2 server.js`) that starts, clusters, monitors, and restarts as necessary
  - We could also automatically add trace, debug, etc. modules

Might be nice if the user could choose which of the two approaches they want to follow for their app.

**Comment by raggi** [comment]
No, do not add a process manager. That is never the job of the container.

**Comment by raggi** [comment]
Justin asked me to expand on this.

I don't want to close down feature discussions, however, the application of a process manager has various implications that are important. We should try to separate the discussion into two distinct parts, one is the desire for specific features (an example might be the desire for something to handle .env files), and the desire for specific system behaviors. Most of my concerns with adding arbitrary process managers are around poor system behaviors, and I very much want to support as many features as is reasonable.

The goal of the control systems and management portions of the App Engine infrastructure are to provide users with a system that is fault tolerant and scalable. The system should identify common faults and make best effort attempts to operate despite them. This works extremely well in App Engine Standard today, and is coming along very well in the App Engine Flexible environment. Part of this control plane relies on the system receiving fault signals from parts of the system that are faulting. Internal systems are very well instrumented to achieve this.

Signals from the application are more complex. Applications making use of stackdriver provide additional signals, but the single most portable and acutely accurate signal is that of an application crashing. There are, as I'm sure you're aware, many possible reasons for this. Some of those reasons may be a problem on the VM, or even inside the container. If we have process managers as the executed program inside the container, we will receive no such signals, and App Engine can do nothing to schedule new VMs and fix the problem. This is the single most important aspect of the behavioral side of this discussion.

As a next area of system behaviors, we have various contracts in App Engine runtimes for how logs are output, for how capabilities are enabled or disabled, setting resource limits and so on. Some process managers will not affect any of this, but some will, as they will alter these things themselves, often these are features that are useful in less managed environments in which those process managers were designed to help. Today, features such as cloud debugger work in concert with the runtimes, but in future we may be able to provide more sophisticated offerings by externally attaching to running processes. In cases such as this, a user would find themselves attaching to the wrong process.

Clustering and subprocesses are always going to be a challenge for dynlang runtimes that need them. Most clustering solutions, luckily, and unlike most process managers, do not detach from their child processes / process group. By contrast a lot of process managers do. A cluster-aware debugger would most likely rely on a process group or subprocesses, although there may be more options in the lxc world in future.

Regarding re-running the docker image entrypoint, we may want to make this configurable, however, it is currently very rare that this would do anything too strange. It makes sense from an optimization standpoint to attempt this at least once, but to fail the whole VM if it fails, after some number of retries in a given period.

If we start playing with process managers, if we really decide that's what people want and need, we should use one that has the behaviors we need, and use it for all runtimes. Process managers are tricky to get right, and typically done wrong. Node itself seems to have buggy waitpid behavior, so writing a stable child process monitor in node is going to be inherently tricky to begin with, for one such example. In case other examples are required, you may observe the leak issues in `god` a popular ruby process manager, and the zombie issues in `bluepill` another that was written to avoid the issues with `god`.

**Comment by MarkHerhold** [comment]
I love PM2 but please do not bundle it with the container by default.
